### PR TITLE
Add Linajex to be an agency Partner

### PR DESCRIPTION
**Pull request by calonsoli**

### CODE REVIEW

**Comment by calonsoli** [comment]
Please add Linajex.com to be an Agency.
You can check on our main page https://linajex.com/index_en.html a direct link to openmage https://linajex.com/openmage_en.html

If something more is needed, please don´t hesitate to tell us.
Best,

**Comment by fballiano** [comment]
@Flyingmana is the info provided correct?

**Comment by Flyingmana** [comment]
@calonsoli thank you for your support. Only one thing, the `contributions` part is to highlight what was contributed to OpenMage by our partners, less to promote what they offer to their customers.
Althought we might add a field for this in the future for our sponsors (we are still in discussion about what to connect towards sponsoring regarding listings)

**Comment by calonsoli** [comment]
deleted!

**Pull request merged**
