### PR TITLE
Add Blackfire to partners

### PR DESCRIPTION
**Pull request by ChristopheDujarric**

### CODE REVIEW

**Comment by tmotyl** [comment]
Hi @ChristopheDujarric 
Thanks for stepping by :)
I think that backfire would be very useful for M1 development.
Do you have a partnership program OpenMage could get involved with Blackfire to find synergies?
For example idea would be that OpenMage would showcase the Blackfire usage, and how it already helped fix some performance issues like the one where we managed to speed up a report generation by 90%, on the other hand Blackfire would provide a license for OpenMage maintainers for profiling the OpenMage core.
Maybe you have other ideas?

**Comment by ChristopheDujarric** [comment]
Hi @tmotyl ! As a matter of fact, while submitting this I sent an email to @LeeSaferite (I just picked the first shown contributor on https://github.com/OpenMage/magento-lts), right about this!

There's definitely some room for collaboration, Blackfire supporting OpenMage with a free access (only for Open Source dev ;) ), and OpenMage contributing to building/improving Magento 1 specific https://blackfire.io/docs/reference-guide/recommendations. We have an existing list, but there's always room for improvement :)

**Comment by Adel-Magebinary** [comment]
Awesome boys. welcome.

**Comment by colinmollenhour** [comment]
Thanks and welcome, Christophe!

Note to self, check more carefully for syntax errors... ;-)

**Comment by sreichel** [comment]
> There's definitely some room for collaboration, Blackfire supporting OpenMage with a free access (only for Open Source dev ;) ), and OpenMage contributing to building/improving Magento 1 specific https://blackfire.io/docs/reference-guide/recommendations. We have an existing list, but there's always room for improvement :)

Hi,

is there already a free access?

Regards

**Comment by ChristopheDujarric** [comment]
Not yet, I'm waiting for feedback from @colinmollenhour :)

**Comment by colinmollenhour** [comment]
Sorry for the silence, @ChristopheDujarric, I just sent you and @sreichel and email.

**Comment by ChristopheDujarric** [comment]
Thanks a lot Colin!

**Pull request merged**
