### PR TITLE
New partner Omny Checkout

### PR DESCRIPTION
**Pull request by omnybrasil**

### CODE REVIEW

**Comment by fballiano** [comment]
There's nothing about openmage on your website so, sorry but it's a no for me.

**Comment by Flyingmana** [comment]
@omnybrasil your online presence is still quite new, do you have an example where Omny Checkout is already used in a production store?

**Comment by omnybrasil** [comment]
We are starting our checkout company and we will adapt to the mentioned parameters.
Our checkout has transacted over $200M in the last few years.
We’ve been working with Magento since 2009 and decided to focus on developing our own checkout service.
We are upgrading all of our Magento 1 clients to OpenMage.
We will provide some case studies soon.
Thanks

**Comment by fballiano** [comment]
please reopen this PR when there will be some material about openmage on your website

**Pull request closed without merging**
