### PR TITLE
Update agency.json - added inchweb

### PR DESCRIPTION
**Pull request by Inchpoint**
Added inchweb - module development agency for magento lts. Last module - Paypal Checkout.

### CODE REVIEW

**Comment by Inchpoint** [comment]
Here are some pages about Magento / Openmage on our website:

https://www.inchweb.de/unsere-dienstleistungen-fuer-magento-kunden.html
https://www.inchweb.de/unsere-erfahrung-magento.html
https://www.inchweb.de/magento-paypal-checkout.html

**Comment by Inchpoint** [comment]
@fballiano @Flyingmana hello there! If you have some time, could you please look at my commit?

**Comment by fballiano** [comment]
if only I'd see the same amount of participation when we need help...

**Comment by Inchpoint** [comment]
> if only I'd see the same amount of participation when we need help...

@fballiano Thats valid point. Better start to participate late, than never. Any chance to do it now?

**Comment by fballiano** [comment]
https://github.com/openmage/magento-lts/ is open for any contribution

**Comment by Flyingmana** [comment]
> Here are some pages about Magento / Openmage on our website:
> 
> https://www.inchweb.de/unsere-dienstleistungen-fuer-magento-kunden.html https://www.inchweb.de/unsere-erfahrung-magento.html https://www.inchweb.de/magento-paypal-checkout.html

The mentioning on the website looks good enough for me.

Having someone providing and supporting a paypal checkout module is a valuable service, I made also a note in our Module overview in our documentation.
https://github.com/OpenMage/documentation/blob/main/modules/payment.rst (visible at https://openmage.readthedocs.io/en/latest/modules/payment.html#paypal )


For participating more, there are many ways you could help. The most direct ones would be by helping with submitting PullRequests but also helping with Reviewing them.
The topics where we especially are searching for help are marked with the [help wanted](https://github.com/OpenMage/magento-lts/pulls?q=is%3Apr+is%3Aopen+label%3A%22help+wanted%22) Label.
If you are unsure about the amount, helping to review 2 PullRequests per month would be a healthy and appreciated contribution.

Please also dont hold back with writing Requests for everything, which might make it easier for you to work with or market OpenMage to Customers.

**Review by Flyingmana — APPROVED** [review]

**Comment by Inchpoint** [comment]
@Flyingmana @fballiano hello there! We are having some free capacities at the moment and are ready to participate and help. What are the most important topics at the moment? (is:pr is:open label:"help wanted" shows zero results.)

**Comment by Flyingmana** [comment]
Ho @Inchpoint 
currently the driving people are @ADDISON74 @sreichel @colinmollenhour 
Maybe they can point you where currently support is appreciated.

**Comment by sreichel** [comment]
Hi @Inchpoint 

thanks for wanting to help.

I think the most important tasks are to review open PRs and issue. Maybe create PRs to fix them.

Other possible tasks are to fix phpstans baselined errors or (as soon my PR is merged) add more unit tests.

(Will merge this PR later)

**Comment by ADDISON74** [comment]
@Inchpoint - You can also take a look in the [Discussions > Ideas](https://github.com/OpenMage/magento-lts/discussions/categories/ideas). By adding functionalities to OpenMage let's hope that we will benefit from the help of other interested people.

**Comment by sreichel** [comment]
@Inchpoint https://www.inchweb.de/files/inchweb/img/logo_inchweb.png isnt available. Please add to https://github.com/OpenMage/OpenMage.github.io/tree/main/assets/images/...

**Pull request merged**
