### PR TITLE
Add rackSPEED as partner

### PR DESCRIPTION
**Pull request by rackspeed**

### CODE REVIEW

**Comment by fballiano** [comment]
I don't see anything about openmage on your website...

**Comment by rackspeed** [comment]
I didn't know it was a requirement as the previous partners like maxcluster.de, splendid-internet.de and jetrails.com don't have anything on their site either. 

As it's just an upgraded Magento that our customers are already using, which is how I found out about you, I don't see any problem with the listing.

How do we proceed now? Do I need to create a special page, will the existing partners be removed or are there any other reasons why I should not be activated?

I look forward to your reply.

**Comment by fballiano** [comment]
I don't decide anything here but I'm against 90% of the partners listed because almost nobody supports openmage in any way.

**Comment by rackspeed** [comment]
That's a shame, because we were the first hoster in Germany to specialise in Magento back in 2008. All the others came after us.

But let's leave that alone, if you already have enough partners, everything is fine. Why continue to support the old hype :)

I just don't understand why this option exists at all.

Best regards

**Comment by fballiano** [comment]
again, I didn't decide the partners nor I decide if this PR gets merged or not. but, as a personal preference, I think that the companies who want to be partners, at least should have something on their website, instead of the big magento2 logo you know.

**Comment by rackspeed** [comment]
As I said, I found out about OpenMage through a client. Personally, I would love to see all Magento 1 clients switch to OpenMage, it would save us a lot of work in terms of hacks and other problems. The client in question did this in less than 24 hours, which impressed me.

While reading the website, I saw that you could sign up as a partner. As there was no list of requirements and nothing on the pages of the partners already listed, I thought I was doing everything right. Of course we are going to promote OpenMage so that our customers know about it, we will create the website shortly.

It was not planned that a simple pull request would be discussed like this. I was less interested in advertising, I wanted to signal that OpenMage works for us when our customers surf your site and thus increase the incentive to start the project.

Maybe it will work with the entry, if not, the website and information to our customers will have to suffice :)

**Comment by fballiano** [comment]
I just expressed my opinion, I think partners should have at least some small something on their website about openmage, that's it.

**Comment by Flyingmana** [comment]
> I didn't know it was a requirement as the previous partners like maxcluster.de, splendid-internet.de and jetrails.com don't have anything on their site either. 
> 
> As it's just an upgraded Magento that our customers are already using, which is how I found out about you, I don't see any problem with the listing.
> 
> How do we proceed now? Do I need to create a special page, will the existing partners be removed or are there any other reasons why I should not be activated?
> 
> I look forward to your reply.

Its a soft requirement, and a sign of politeness to have something provided in regard to Openmage.

https://maxcluster.de/faq-magento1-end-of-life
and several more to find via google

https://www.splendid-internet.de/magento-hosting/openmage-30-tage-testversion
and several more to fond via google

https://jetrails.com/blog/magento-1-security-updates/
at least something


But thats only one of the possible things.
Some of the Partners also offer hosting capacity, or provide other contributions, or simply help with marketing by making OpenMage a recognized Option.


But also, its good for OpenMage users to see there is a collection of different Hosting companies actually knowing about OpenMage and having experience with hosting it.

You definitely have experience with Magento after so many years 🙂
So usually I also accept a promise to provide us semi-regularly with feedback of your users and their needs, so we know what changes could help them (and also from you as a hoster to make hosting related maintenance easier)
And even better if you have sometimes patches and improvements you can contribute to our code.

**Comment by sreichel** [comment]
Little late, :rofl: 

Worked with @rackspeed from 2011 for years :+1:  :)

Some advertising on your website would be nice. Or even better an instance to automatocally deploy PRs for testing ;)

**Comment by sreichel** [comment]
@Flyingmana @colinmollenhour @fballiano?

**Comment by sreichel** [comment]
> what exactly do you need

A _nice to have_ would be ....

A deploy script and wildcard subdomains for something like...? 

- `[pr-xyz].rackspeed-openmage.de`
- `[branch-xyz].rackspeed-openmage.de`

... a script that resets DB after time ...

**Comment by rackspeed** [comment]
First of all, I must apologise. I did not receive the email notification or missed it.

As far as the hardware is concerned, we can deliver at short notice because that is our job. Unfortunately, it doesn't look so good for script development as we are currently planning a major rebuild. Looking at the PR, I am sure you have people in your team who can do this better and faster :)

However, cPanel does offer an API that allows you to do things in the account via Bash, PHP and Perl, including managing subdomains and databases.

https://api.docs.cpanel.net/openapi/cpanel/operation/create_database/
https://api.docs.cpanel.net/openapi/cpanel/operation/addsubdomain/

**Comment by Flyingmana** [comment]
> > what exactly do you need
> 
> A _nice to have_ would be ....
> 
> A deploy script and wildcard subdomains for something like...?
> 
> * `[pr-xyz].rackspeed-openmage.de`
> * `[branch-xyz].rackspeed-openmage.de`
> 
> ... a script that resets DB after time ...

we do have a deploy script already, it would just need to be modified for the environment rackSPEED uses and how the deployed directory is constructed.

And creating an github action which resets the database should be comparable simple.

**Review by sreichel — APPROVED** [review]

**Comment by Flyingmana** [comment]
> > Some advertising on your website would be nice.
> 
> in progress :)
> 
> > Or even better an instance to automatocally deploy PRs for testing ;)
> 
> With pleasure, what exactly do you need (CPU / RAM / Disk)? I can offer a server with cPanel and possibly Elasticsearch at short notice. Apache 2.4 will be used as the web server, Litespeed would also be possible.

Sorry for not checking back for so long, was there any progress on mentioning on the website?
I will merge it anyway now already as there was enough approval on our side 🙂

**Pull request merged**
