### PR TITLE
Added vicus to as agency and hosting

### PR DESCRIPTION
**Pull request by vicuseb**
Added Vicus to agency.json and hosting_provider.json

### CODE REVIEW

**Comment by vicuseb** [comment]
@Flyingmana I was wondering if this could please be merged.

**Comment by fballiano** [comment]
@vicuseb do you have anything about openmage on your website?

**Comment by vicuseb** [comment]
@fballiano https://www.vicus.nl/partner/openmage-lts/

**Comment by vicuseb** [comment]
@Flyingmana @fballiano Can we be merged and added to the page please?

**Comment by Flyingmana** [comment]
sorry for letting you wait so long, its merged now

**Pull request merged**
